import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Decentralised File Storage</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='container w-600 my-96'>
				<h2 className='text-6xl font-extrabold text-center'>
					Welcome to Dinata
				</h2>
				<p className='text-center text-2xl mt-8'>
					The number one decentralised file storage built on web3
				</p>
				<button className='flex justify-center items-center mt-10 bg-sky-500 p-5 w-full text-2xl rounded-lg hover:bg-sky-900'>
					Login
				</button>
			</main>
		</div>
	);
};

export default Home;
