import type { NextPage } from 'next';
import Head from 'next/head';
import toast, { Toaster } from 'react-hot-toast';
import WalletContext from 'context/wallet/WalletContext';
import { useContext, useEffect } from 'react';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
	const walletContext = useContext(WalletContext);

	const { connectWallet, message, error, clearMessage, clearError } =
		walletContext;
	const router = useRouter();

	//Handle Messages
	useEffect(() => {
		let mounted = true;

		if (mounted && message !== null) {
			toast.success(message);
			setTimeout(() => clearMessage(), 3000);
		}
		return () => {
			mounted = false;
		};
		//eslint-disable-next-line
	}, [message]);

	//Handle Errors
	useEffect(() => {
		let mounted = true;

		if (mounted && error !== null) {
			toast.error(error);
			setTimeout(() => clearError(), 3000);
		}
		return () => {
			mounted = false;
		};
		//eslint-disable-next-line
	}, [error]);
	return (
		<div>
			<Head>
				<title>Decentralised File Storage</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Toaster position='top-right' />

			<main className='container w-600 my-96'>
				<h2 className='text-6xl font-extrabold text-center'>
					Welcome to Dinata
				</h2>
				<p className='text-center text-2xl mt-8'>
					The number one decentralised file storage built on web3
				</p>
				<button
					className='flex justify-center items-center mt-10 bg-sky-500 p-5 w-full text-2xl rounded-lg hover:bg-sky-900'
					onClick={() => connectWallet(router)}
				>
					Login
				</button>
			</main>
		</div>
	);
};

export default Home;
